digicampipe/calib/camera/dl0.py
digicampipe/calib/camera/dl1.py
digicampipe/calib/camera/dl2.py
digicampipe/calib/camera/filter.py
digicampipe/calib/camera/r1.py
digicampipe/calib/camera/random_triggers.py
digicampipe/io/containers.py
digicampipe/io/event_stream.py
digicampipe/io/protozfitsreader.py
digicampipe/io/zfits.py
digicampipe/utils/geometry.py
digicampipe/utils/utils.py
pipeline2.py

the DataContainers have new elements some are moved to other containers to respect ctapipe framework.
new element in pipeline are filling informations (like baseline and flags they are temporary since it should be provided from DigiCam). Filters allow to separate data from calibration data.

DataContainers reviewed and pipeline more flexible

---

.travis.yml
requirements.txt

There was still a problem with the dependencies of "rawzfitsreader.[...].so".
They should now be solved in protozfitsreader v.0.41.1 which is installed after this PR

Install protozfitsreader v0.41.1

---

.travis.yml

testing deploy feature with Travis. Need to be merged with master to trigger documentation deployement

Docu ghpage

---

digicampipe/image/cones_image.py
digicampipe/image/sky_image.py
digicampipe/image/utils.py
digicampipe/tests/test_lid_ccd.py

replace asterisk imports by explicit imports.
Also sort imports according to:
* std-libary
* dependencies, we have not written ourselves
* our own stuff

Lid ccd imports

---

digicampipe/image/cones_image.py
digicampipe/image/kernels.py
digicampipe/image/nova_client.py
digicampipe/image/sky_image.py
digicampipe/image/utils.py
digicampipe/tests/test_cone_simu.py
digicampipe/tests/test_lid_ccd.py

Lid ccd pep8

---

README.md
digicampipe/tests/test_cone_simu.py
digicampipe/tests/test_lid_ccd.py
quick_test.ini

allow for faster local testing if slow tests are not wanted:
Execute tests as: 
user@host:~/ctasoft/digicampipe$ pytest -c quick_test.ini digicampipe

allow for faster local testing

---

digicampipe/utils/__init__.py
digicampipe/utils/tests/test_camera.py

fixes #80 if we want that
merging this PR does not change anything for existing code. So it is safe to merge. 
Oh . tests are missing .. damn ... gimme a sec

utility class "Camera" for "cts_core.camera.Camera"

---

environment.yml

Adding docopt to environment.yml. Which version is needed?
Reported by @sagreus

add docopt

---

digicampipe/calib/camera/dl1.py
digicampipe/io/save_hillas.py
environment.yml

Jurysek simtel2 pep8 dneise

---

environment.yml

Also updating from v0.5 to v0.7 ... 
Fix for #129 
Waiting for tests  to pass, I guess we can merge then

Install sphinx_automodapi using pip.

---

spe.py

I reviewed spe.py (only formally not regarding the contents) ... and tidied it up a bit.

Tidy up spe py

---

digicampipe/scripts/spe.py
digicampipe/tests/test_spe.py
setup.py
spe.py

This should be merged only after #169 is merged.

Spe py in scripts to make it testable

---

digicampipe/scripts/spe.py

This tries to fix #174.
It builds on top of the other PR #173. So whoever reviews this one here, should review maybe #173 first.
Both are pretty short.

Speed up spe

---

digicampipe/scripts/spe.py

I used this parameter in a study I've shown in #175 already. 
So ... shame on me .. I showed results, which nobody can reproduce ... based on code I did not check in.
So here now I propose this version with `shift` in spe.py used by compute_charge

add shift_parameter

---

digicampipe/scripts/spe.py

I need to be able to set the threshold of the pulse finder for some study of mine...

expose threshold

---

.travis.yml
README.md
environment.yml
requirements.txt

Having an environment.yml and a requirements.txt seems one file too much.

Remove requirements txt

---

.travis.yml

fix path error

---

digicampipe/io/containers_calib.py
digicampipe/io/event_stream.py

Added local_time to the CalibrationContainer. Please double check for consistency before merge.

added local_time to CalibrationContainer

---

digicampipe/io/auxservice.py
digicampipe/io/event_stream.py

It seems now the slow data fit files are gziped, so few modifications were needed.
@dneise I also changed the set into a list as I had errors there and tried to make the error more explicit.
Let me know if I did something wrong there.

fixing slow data

---

digicampipe/scripts/raw.py
digicampipe/visualization/plot.py

Baseline in digicamraw

---

bash/template_scan_analysis.sh
bash/time_resolution.sh
digicampipe/scripts/pulse_shape.py
digicampipe/scripts/pulse_template.py
digicampipe/scripts/time_resolution.py
digicampipe/tests/test_pulse_template_object.py
digicampipe/utils/hist2d.py
digicampipe/utils/pulse_template.py
digicampipe/visualization/time_resolution_plot.py

Few improvements (including tests) and bash script to demonstrate template creation.

bash script with pulse template creation from scratch

---

digicampipe/scripts/bad_pixels.py
digicampipe/tests/test_bad_pixels.py

Determine bad pixels from a calibration file.

Bad pixels

---

digicampipe/io/containers.py
digicampipe/io/event_stream.py
digicampipe/io/hessio.py
digicampipe/tests/test_simtel_event_source.py
setup.py

Updated reader so it can be used by calibration container as well.
Created tests as well.

reader filling callibration containers

---

digicampipe/calib/baseline.py
digicampipe/calib/trigger.py
digicampipe/io/hdf5.py
digicampipe/scripts/rate_scan.py
digicampipe/scripts/raw.py
digicampipe/tests/test_rate_scan.py

This PR modifies the rate_scan. Example usage : 
```bash
digicam-rate-scan --compute --threshold_step=1 --threshold_end=4095 --threshold_start=0 --figure_path=rate_scan.png --output=rate_scan.fits /sst1m/rsync_data/raw/2018/11/07/SST1M_01/SST1M_01_20181107_0178.fits.fz
```

Bias curve data

---

bash/template_scan_analysis.sh
bash/time_resolution.sh
digicampipe/scripts/time_resolution.py
digicampipe/utils/pulse_template.py
digicampipe/visualization/time_resolution_plot.py

Adapt scripts to produce the pulse template and timing resolution plots for the calibration paper.

 calibration paper plots
